### ISSUE TITLE
Need Rax kitchen sink examples for common storybook add-on

### ISSUE THREAD

**Issue by trongthanh** [raxland/storybook#5]
There are a few key add-ons from storybook. We need more examples in `examples/rax-kitchen-sink` that showcase these add-ons and help other developer to make use of them:

- [x] Notes (next to Canvas)
- [x] Story source (add @storybook/addon-storysource, but not working on my side)
- [x] Actions (Button already demo-able)
- [x] Events (unsure if this is applicable for Rax)
- [x] Knobs
- [x] Links
- [x] Accessibility
- [x] Tests
- Others if necessary

**Comment by hoanguyen311** [comment]
- [x] Add support for Center addon

**Comment by hoanguyen311** [comment]
DONE
